### ISSUE TITLE
Maximized windows end up behind panels after screen going off

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2580]
~~Don't have a clear reproducer, but I can sometimes see maximized windows going under panels~~

1. start a Miriway session as configured below
2. let the screen go to sleep (may want to reduce `idle-timeout`
3. wake the screen up
4. maximize a window

![frame_2022-08-25T10:00+02:00](https://user-images.githubusercontent.com/231077/186609600-e2aefd7a-f11b-404d-b77c-334a879c99aa.png)

Using this [Miriway](https://github.com/Miriway/Miriway) config:

```ini
x11-window-title=Miriway
idle-timeout=180
ctrl-alt=t:miriway-terminal # Default "terminal emulator finder"

enable-x11=true
display-config=static=/home/michal/.config/miriway.display

shell-component=swaybg -i /usr/share/backgrounds/warty-final-ubuntu.png
shell-component=mate-panel
meta=a:mate-panel --run-dialog
ctrl-alt=t:mate-terminal
```

```yaml
layouts:
  default:
    cards:
    - card-id: 0
      eDP-1:
        position: [1920, 0]
      DisplayPort-1:
      HDMI-A-1:
```
