### ISSUE TITLE
Excessive load when surface draws with multiple displays configured

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2582]
Mir uses excessive amounts of CPU when redrawing (more than twice what gnome-shell uses in the same scenario). It seems to be related to multiple displays (maybe redrawing the second, untouched, display unnecessarily?).

Can be seen by e.g. `while true; do sleep .01; echo .; done` in a terminal window maximized on one output. Reconfiguring to a single output more than halves the load.

With a display config:

```yaml
layouts:
  default:
    cards:
    - card-id: 0
      eDP-1:
        position: [1920, 0]
      DisplayPort-1:
      HDMI-A-1:
```
(eDP-1 at 1920x1080@60; DisplayPort-1 at 1920x1200@60)
