### ISSUE TITLE
Cross-building stopped working…

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2737]
E.g. https://github.com/MirServer/mir/actions/runs/3620078581/jobs/6101888076:

```yaml
output-version: 1.2
native-architecture: amd64
foreign-architecture: armhf
report:
 -
  package: sbuild-build-depends-main-dummy
  version: 0.invalid.0
  architecture: armhf
  status: broken
  reasons:
   -
    missing:
     pkg:
      package: sbuild-build-depends-main-dummy
      version: 0.invalid.0
      architecture: armhf
      unsat-dependency: eglexternalplatform-dev:all
```
