### ISSUE TITLE
Screenshotting not scale aware

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2760]
Given the display config:

```yaml
layouts:
  default:
    cards:
    - card-id: 0
      unknown-1:
        scale: 2
      unknown-2:
        mode: 1280x720@60.0
        position: [2560, 0]
```
And ran as:
```
$ ubuntu-frame --x11-output 2560x1440:1280x720
```

The screenshot is messed up (NB: the middle is transparent):
![frame_2023-01-04T17:28+01:00](https://user-images.githubusercontent.com/231077/210607918-871674d1-44e4-449a-8bdf-54286127e4e9.png)

Looks like, when compositing, the output scale isn't applied.
