### ISSUE TITLE
Building Frame snap for Mir PRs fails

### ISSUE THREAD

**Issue by AlanGriffiths** [MirServer/mir#2877]
I can see the problem comes from the migration to `20` and `22` tracks, but not why.

The error we get is:

> 2023-03-24 10:52:38.905 :: 2023-03-24 10:52:38.585 subprocess.CalledProcessError: Command '['snap', 'download', 'mir-libs', '--channel', 'latest/edge/pr2734/22/edge']' returned non-zero exit status 1.

And I can see why this would be in snaps (such as `confined-shell` and `mir-test-tools`) who have a `mir-libs-build` branch with:

```yaml
parts:
  mir:
    plugin: nil
    stage-snaps:
      - mir-libs/22/edge
```

Because the following doesn't allow for track & risk being mentioned already:

```yaml
    - name: Tweak the stage snap
      run: |
        sed -i 's@- mir-libs@\0/latest/edge/pr${{ github.event.number }}@' snap/snapcraft.yaml
```

But _those_ snaps build fine while Frame (which just has `- mir-libs`) fails. I'm confused!
