### ISSUE TITLE
Cursor size getting confused when scaled over some apps

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#2944]
Using this display config:
```yaml
layouts:
  default:
    cards:
    - card-id: 0
      eDP-1:
        scale: 1.5
```

When I move the cursor over Element or Telegram, the cursor is like 3x the size.
