### ISSUE TITLE
rendering: scaling one display affects rendering on the other

### ISSUE THREAD

**Issue by Saviq** [MirServer/mir#3171]
With a couple displays, I have a setup like so:

```yaml
layouts:
  default:
    cards:
    - card-id: 0
      eDP-1:
        position: [1920, 0]
        scale: 1.25
      DisplayPort-1:
```

So the left-most display is unscaled, at `0,0`.

If I change the `scale`, I can clearly see it badly affecting my unscaled display, suggesting that the applications get told to scale at the other display's scale, and then get scaled back.

---

The reason for this is we are not tracking the outputs the surface is on. All we do is send an "enter" for every output when the window is created.

https://github.com/MirServer/mir/blob/bc6864bc7b2575b445355dcd63a2b3525be68458/src/server/frontend_wayland/window_wl_surface_role.cpp#L472
